openapi: 3.1.0
info:
  title: Customer API
  version: '1.0'
  description: ''
  summary: Read and Update Data Related to Customers
servers: []
paths:
  '/api/v1/customers/{customerId}/appeasements':
    parameters:
      - schema:
          type: string
          example: d28f2a3e-432a-454b-93c2-540ace3192bf
        name: customerId
        in: path
        description: The id of the customer the appeasements are associated to
        required: true
    get:
      summary: Get Appeasements By Customer ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Indicates whether the request completed successfully
                    example: success
                    enum:
                      - success
                      - failure
                      - error
                  data:
                    type: object
                    required:
                      - content
                    properties:
                      content:
                        type: array
                        items:
                          type: object
                          properties:
                            customerId:
                              type: string
                              description: The ID of the customer who was given the appeasement
                              format: uuid
                              example: d28f2a3e-432a-454b-93c2-540ace3192bf
                            customerEmail:
                              type: string
                              description: The email of the customer who received the appeasement
                              format: email
                              example: example@finishline.com
                            amount:
                              type: number
                              example: 19.99
                              description: The amount of the appeasement
                            reasonCode:
                              type: string
                              description: A code that indicates the reason for the appeasement
                              example: SHIP REF REQ
                            createdByUserId:
                              type: string
                              description: The id of the user who created the appeasement
                              example: C123456
                            createdByName:
                              type: string
                              description: The full name of the person who created the appeasement
                              example: John Doe
                            comments:
                              type: string
                              description: Comments entered by the user when the appeasement was created with additional information as to why the appeasement was created
                              example: The customer was upset that their shipment was late.
                            orderDate:
                              type: string
                              description: The order date (ISO 8601) of the order this appeasement is associated with
                              format: date
                              example: '2020-02-05'
                            orderNumber:
                              type: string
                              description: The order number of the order this appeasement is associated with
                              example: FNL-CO-123456789
                            createdDateTime:
                              type: string
                              description: A timestamp (ISO 8601) that indicates when the appeasement was created
                              format: date-time
                              example: '2022-03-03T15:27:37.375Z'
                          required:
                            - customerEmail
                            - amount
                            - orderDate
                            - orderNumber
                            - createdDateTime
                required:
                  - status
                  - data
              examples:
                example:
                  value:
                    status: success
                    data:
                      content:
                        - customerId: d28f2a3e-432a-454b-93c2-540ace3192bf
                          customerEmail: example@finishline.com
                          amount: 19.99
                          reasonCode: SHIP REF REQ
                          createdByUserId: C123456
                          createdByName: John Doe
                          comments: The customer was upset that their shipment was late.
                          orderDate: '2020-02-05'
                          orderNumber: FNL-CO-123456789
                          createdDateTime: '2022-03-03T15:27:37.375Z'
      operationId: get-api-v1-customers-customerId-appeasements
      description: Get a list of appeasements associated with the customer
      parameters:
        - schema:
            type: string
            example: '5'
            default: '0'
          in: query
          name: page
          description: The 0 based index of the page to return
        - schema:
            type: string
            example: '10'
            default: '20'
          in: query
          name: pageSize
          description: The max number of appeasements to return
        - schema:
            type: string
            default: 'createdDateTime,asc'
            example: 'amount,desc'
          in: query
          name: sort
          description: The column and direction to sort the appeasements by (multiple sort criteria are supported)
components:
  schemas: {}
  securitySchemes: {}
